version: "3.9"

services:
  discord_bot:
    container_name: discord_bot
    image: discord_bot
    build:
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: always